name: Feature Request
description: Propose a new feature, improvement, or idea for RouteLens.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We appreciate feature suggestions! Please explain the problem you are trying to solve.
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Is your feature request related to a specific network monitoring problem?
      placeholder: I am always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
